# Generated by Django 2.2.6 on 2019-11-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='subject',
            field=models.CharField(help_text='게시물 제목', max_length=70),
        ),
    ]
