# Generated by Django 2.2.7 on 2019-11-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subject',
            field=models.CharField(help_text='게시물 제목', max_length=255),
        ),
    ]
