# Generated by Django 2.2.7 on 2019-11-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20191110_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subject',
            field=models.CharField(help_text='게시물 제목', max_length=128),
        ),
    ]
