# Generated by Django 2.2.7 on 2019-11-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20191110_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.CharField(help_text='썸네일 이미지 URL', max_length=255, null=True),
        ),
    ]
